### ISSUE TITLE
Mise à jour rapide et automatique du contenu

### ISSUE THREAD

**Issue by emmanuelamicel** [isogeo/doc-homepage#11]
## Problème

Depuis le passage de l'aide en ligne en HTTPS, Isogeo utilise un système appelé un _Azure CDN_ (pour Content Delivery Network), qui copie en cache les fichiers et dossiers contenus dans l'Azure Blob Storage qui contient tous les fichiers de tous les repositories de l'aide en ligne. Plus d'informations ont été rédigées ici : https://github.com/isogeo/doc-homepage/wiki/https.

**Problème :** l'aide en ligne n'est pas mise instantanément à jour lorsqu'une modification est mise en production et validée par les pipelines Azure DevOps. Le soucis doit venir de l'absence de vidage du cache. En général, les modifications sont quand même affichées une à deux heures plus tard (à confirmer).

Pour résoudre cette issue, des informations sont peut-être disponibles sur cette page de la documentation Microsoft : https://docs.microsoft.com/fr-fr/azure/architecture/serverless/guide/serverless-app-cicd-best-practices.

Une idée à exploiter serait de modifier les pipelines Azure DevOps du projet Documentation en ajoutant l'exécution à la fin de la pipeline d'une requête Azure qui viderait le cache du point de terminaison. Chaque pipeline serait configurée pour ne vider que le dossier dans lequel elle publie.

## Vider le cache

Si une mise en production a lieu et que les changements ne sont pas disponibles tout de suite :

* se rendre sur le [point de terminaison de l'aide en ligne](https://portal.azure.com/#@isogeo.fr/resource/subscriptions/82885610-5841-4749-8d71-46f56b643ad2/resourceGroups/isogeo/providers/microsoft.cdn/profiles/isogeo-help/endpoints/prodisogeohelp/overview),
* cliquer sur le bouton "Vider" (ou "Purge"), et sélectionner le bouton "Vider tout",
* attendre quelques minutes, et dans un nouvel onglet en navigation privée, vérifier que le contenu a bien été mis à jour.

## Travail à effectuer

Ajouter à chaque pipeline de documentation une nouvelle tâche AzureCLI qui prendra cette forme :

```yaml
- task: AzureCLI@1
  displayName: Purge endpoint cache
  inputs:
    azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge --resource-group isogeo --profile-name isogeo-help --name prodisogeohelp --content-paths /admin/* --no-wait'
```

Modifier selon le repository le chemin d'accès à vider. Vous pouvez trouver la liste des chemins d'accès en consultant [le contenu du Blob Storage](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2F82885610-5841-4749-8d71-46f56b643ad2%2FresourceGroups%2Fisogeo%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fprodisogeohelp/path/%24web/etag/%220x8D618C21CF9FB53%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None).

**A regarder :** vérifier qu'il n'y a pas une règle supplémentaire à appliquer sur le CDN pour faire en sorte que le navigateur de l'utilisateur se mette à jour automatiquement aussi (pour qu'on ait pas à lancer l'aide en ligne en navigation privée pour avoir les dernières modifications).

**Comment by emmanuelamicel** [comment]
## Travail à effectuer

Ajouter à chaque pipeline de documentation une nouvelle tâche AzureCLI qui prendra cette forme :

```yaml
- task: AzureCLI@1
  displayName: Purge endpoint cache
  inputs:
    azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge --resource-group isogeo --profile-name isogeo-help --name prodisogeohelp --content-paths /admin/* --no-wait'
```

Modifier selon le repository le chemin d'accès à vider. Vous pouvez trouver la liste des chemins d'accès en consultant [le contenu du Blob Storage](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2F82885610-5841-4749-8d71-46f56b643ad2%2FresourceGroups%2Fisogeo%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fprodisogeohelp/path/%24web/etag/%220x8D618C21CF9FB53%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None).
